ALTER TABLE "PostgresBackupPolicy"
ADD COLUMN "storageLayout" TEXT NOT NULL DEFAULT 'DATABASE_CENTERED';

ALTER TABLE "MssqlBackupPolicy"
ADD COLUMN "storageLayout" TEXT NOT NULL DEFAULT 'DATABASE_CENTERED';
