import { describe, expect, it } from "vitest";
import ExcelJS from "exceljs";
import { createAnalyticsSession, normalizeExcelValueForDuckDb } from "@/lib/duckdb/engine";
import { excelCellToValue } from "@/lib/duckdb/excel-layout";
import { toHermodType } from "@/lib/duckdb/type-mapper";

async function workbookBuffer(workbook: ExcelJS.Workbook): Promise<Buffer> {
  return Buffer.from(await workbook.xlsx.writeBuffer());
}

describe("Excel cell normalization", () => {
  it("uses cached numeric formula results", () => {
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet("Sheet1");
    worksheet.getCell("A1").value = { formula: "1+1", result: 2 };

    expect(excelCellToValue(worksheet.getCell("A1"))).toBe(2);
  });

  it("returns null for formulas without cached results", () => {
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet("Sheet1");
    worksheet.getCell("A1").value = { formula: "1+1" };

    expect(excelCellToValue(worksheet.getCell("A1"))).toBeNull();
  });

  it("joins rich text into a string", () => {
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet("Sheet1");
    worksheet.getCell("A1").value = {
      richText: [{ text: "Hello" }, { text: " " }, { text: "world" }],
    };

    expect(excelCellToValue(worksheet.getCell("A1"))).toBe("Hello world");
  });

  it("uses hyperlink display text", () => {
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet("Sheet1");
    worksheet.getCell("A1").value = {
      text: "Invoice",
      hyperlink: "https://example.com/invoice",
    };

    expect(excelCellToValue(worksheet.getCell("A1"))).toBe("Invoice");
  });

  it("returns null for Excel error cells", () => {
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet("Sheet1");
    worksheet.getCell("A1").value = { error: "#VALUE!" } as ExcelJS.CellErrorValue;

    expect(excelCellToValue(worksheet.getCell("A1"))).toBeNull();
  });

  it("does not pass unknown objects through to DuckDB rows", () => {
    expect(normalizeExcelValueForDuckDb({ formula: "SUM(A1:A2)" })).toBeNull();
    expect(normalizeExcelValueForDuckDb({ nested: { value: 1 } })).toBeNull();
  });

  it("does not let footer formula rows force numeric columns to JSON", async () => {
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet("Sheet1");
    worksheet.getCell("A1").value = "Item";
    worksheet.getCell("B1").value = "Amount";
    worksheet.getCell("A2").value = "A";
    worksheet.getCell("B2").value = 10.5;
    worksheet.getCell("A3").value = "B";
    worksheet.getCell("B3").value = 20.75;
    worksheet.getCell("A4").value = "Grand Total :";
    worksheet.getCell("B4").value = { formula: "SUM(B2:B3)", result: 31.25 };
    worksheet.getCell("A5").value = "Generated by export";
    worksheet.getCell("B5").value = { formula: "B4" };

    const session = await createAnalyticsSession();
    try {
      await session.loadExcel(await workbookBuffer(workbook), "staging");
      const profile = await session.profileTable("staging");
      const amount = profile.columns.find((column) => column.name === "Amount");

      expect(profile.rowCount).toBe(2);
      expect(amount).toBeDefined();
      expect(toHermodType(amount!.duckdbType)).toBe("FLOAT");
      expect(toHermodType(amount!.duckdbType)).not.toBe("JSON");
    } finally {
      await session.close();
    }
  });
});
